include:
  - template: Auto-DevOps.gitlab-ci.yml
variables:
  AUTO_DEVOPS_DEPLOY_DEBUG: "true"
  AUTO_DEVOPS_COMMON_NAME: "false"
  BROWSER_PERFORMANCE_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  SAST_DISABLED: "true"
  POSTGRES_VERSION: "13"
  DOCKER_HOST: "tcp://docker-dind.gitlab-managed-apps:2375"

test:
  stage: test
  script:
    - echo "tests disabled"
  when: manual

deploy to production-green:
  before_script:
    - printenv ENV_SPECIFIC_VALUES > chart/values.yaml || true
    - echo "$ENV_SPECIFIC_VALUES"
  extends: .auto-deploy
  stage: deploy
  script:
    - auto-deploy check_kube_domain
    - auto-deploy download_chart
    - auto-deploy use_kube_context
    - auto-deploy ensure_namespace
    - auto-deploy initialize_tiller
    - auto-deploy create_secret
    - auto-deploy deploy
  # variables:
  #   COLOR: "dev-green"
  # HELM_UPGRADE_EXTRA_ARGS: >-
  #    --set ingress.annotations[0].key="kubernetes.io/ingress.class"
  #    --set ingress.annotations[0].value="public"
  #    --set ingress.annotations[1].key="cert-manager.io/cluster-issuer"
  #    --set ingress.annotations[1].value="letsencrypt-prod"
  # HELM_UPGRADE_EXTRA_ARGS: |
  #    --set ingress.enabled=false
  # POSTGRES_HELM_UPGRADE_EXTRA_ARGS: >-
  # --set persistence.storageClass=hdd-hostpath
  # --set postgresqlPostgresPassword=$POSTGRES_PASSWORD
  # --set postgresqlPassword=$POSTGRES_PASSWORD
  environment:
    name: production-green
    url: http://$KUBE_INGRESS_BASE_DOMAIN


production:
  environment:
    name: production
    url: http://$KUBE_INGRESS_BASE_DOMAIN
  when: manual