include:
  - template: Auto-DevOps.gitlab-ci.yml
variables:
  AUTO_DEVOPS_DEPLOY_DEBUG: "true"
  AUTO_DEVOPS_COMMON_NAME: "false"
  BROWSER_PERFORMANCE_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  SAST_DISABLED: "true"
  POSTGRES_VERSION: "13"

  DOCKER_HOST: "tcp://docker-dind.gitlab-managed-apps:2375"

test:
  stage: test
  script:
    - echo "tests disabled"
  when: manual

deploy to dev-green:
  stage: production
  variables:
    COLOR: "dev-green"
  script:
    - echo "Deploying to $COLOR environment"
  # HELM_UPGRADE_EXTRA_ARGS: >-
  #    --set ingress.annotations[0].key="kubernetes.io/ingress.class"
  #    --set ingress.annotations[0].value="public"
  #    --set ingress.annotations[1].key="cert-manager.io/cluster-issuer"
  #    --set ingress.annotations[1].value="letsencrypt-prod"
  # HELM_UPGRADE_EXTRA_ARGS: |
  #    --set ingress.enabled=false
  # POSTGRES_HELM_UPGRADE_EXTRA_ARGS: >-
  # --set persistence.storageClass=hdd-hostpath
  # --set postgresqlPostgresPassword=$POSTGRES_PASSWORD
  # --set postgresqlPassword=$POSTGRES_PASSWORD
  environment:
    name: $COLOR
    url: http://$KUBE_INGRESS_BASE_DOMAIN
