apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-service-read-to-gitlab
  namespace: sdaf-cwap-production-services
subjects:
  - kind: ServiceAccount
    name: serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: allow-service-read
  apiGroup: rbac.authorization.k8s.io
