apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-service-read
  namespace: sdaf-cwap-production-services
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "update", "delete"]