apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-clusterrole-reader-to-gitlab
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlab-managed-apps
roleRef:
  kind: ClusterRole
  name: clusterrole-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-service-read-clusterrole
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-allow-service-read-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlab-managed-apps
roleRef:
  kind: ClusterRole
  name: allow-service-read-clusterrole
  apiGroup: rbac.authorization.k8s.io