export enum Key {
  CONTRACT_OWNER = 'CONTRACT_OWNER',
  MAKER_STATE = 'MAKER_STATE',
  MAKER_AVAILABLE_BALANCE = 'MAKER_AVAILABLE_BALANCE',
  ORDER_STATE = 'ORDER_STATE',
  ORDER_COLLATERAL = 'ORDER_COLLATERAL',
  ORDER_OWNER_INDEX = 'ORDER_OWNER_INDEX',
  ORDER_DATE_INDEX = 'ORDER_DATE_INDEX',
  ORDER_BEST_INDEX = 'ORDER_BEST_INDEX',
  ORDER_ACTIVE_INDEX = 'ORDER_ACTIVE_INDEX',
  ORDER_PENDING_INDEX = 'ORDER_PENDING_INDEX',
  ORDER_CLOSED_INDEX = 'ORDER_CLOSED_INDEX',
  REQUEST_STATE = 'REQUEST_STATE',
  REQUEST_FUNDS = 'REQUEST_FUNDS',
  REQUEST_BY_ORDER_INDEX = 'REQUEST_BY_ORDER_INDEX',
  REQUEST_BY_MAKER_INDEX = 'REQUEST_BY_MAKER_INDEX',
}

export enum ORDER_ACTIVITY_STATUS {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum REQUEST_EXECUTION_STATUS {
  PENDING = 'PENDING',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
}

export enum PUBLIC_METHODS {
  DEPOSIT = '0x01',
  WITHDRAW = '0x02',
  CREATE_ORDER = '0x03',
  CHANGE_ORDER = '0x04',
  CANCEL_ORDER = '0x05',
  REQUEST_EXECUTION = '0x06',
  CHANGE_CONTRACT_OWNER = '0x07',
}

export const FEE = {
  CREATE_ORDER: 400000n,
  CANCEL_ORDER: 400000n,
  DEPOSIT: 20000n,
  WITHDRAW: 20000n,
  HANDLE_EXECUTION_REQUEST: 1000000n,
};
