import makeTransaction, { validateTransaction } from '../controllers/makeTransaction';
import { getAllWallets, refreshToken } from '../controllers';
import { saveWallet } from '../controllers';
import express from 'express';
import { getBalanceOfAddress, validateGetBalance } from '../controllers';
import { loginUser } from '../controllers';
import { dropAllAutoTransactions, getAllAutoTransactions, startAutoTransaction, stopAutoTransaction, } from '../controllers/autoTransactor';
import { authenticate } from '../middlewares';
const router = express.Router();
router.post('/save/wallet', authenticate, saveWallet);
router.get('/wallets', authenticate, getAllWallets);
router.post('/transaction', validateTransaction, authenticate, makeTransaction);
router.get('/balance', validateGetBalance, getBalanceOfAddress);
router.post('/login', loginUser);
router.post('/refresh', refreshToken);
// router.get('/create/users', createUsers);
router.post('/auto-send/start', validateTransaction, authenticate, startAutoTransaction);
router.delete('/auto-send/stop/:walletAddress', authenticate, stopAutoTransaction);
router.get('/auto-send/transactions', authenticate, getAllAutoTransactions);
router.get('/auto-send/transactions/drop-all', authenticate, dropAllAutoTransactions);
export default router;
