import { type User } from '@coinweb/wallet-lib';
import { Client } from './types';
export declare const getOrderById: (client: Client, id: string) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    covering: bigint;
    l1Amount: import("./shared").HexBigInt;
    createdAt: number;
    expirationDate: number;
    activityStatus: import("./shared").ORDER_ACTIVITY_STATUS;
    owner: import("@coinweb/contract-kit").User;
    baseRecipient: import("@coinweb/contract-kit").User;
    txId: string;
}>;
export declare const getClaimById: (client: Client, id: string) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    createdAt: number;
    executionStatus: import("./shared").REQUEST_EXECUTION_STATUS;
    expirationDate: number;
    fallbackContractId: string;
    fallbackMethodName: string;
    quoteWallet: string;
    requestedOrderId: string;
    txId: string;
}>;
export declare const getAllOwnOrdersIds: (client: Client, owner: User) => Promise<string[]>;
export declare const getAllOwnClaimIds: (client: Client, owner: User) => Promise<string[]>;
export declare const getAllActiveOrdersIds: (client: Client) => Promise<string[]>;
export declare const getBestOrdersIds: (client: Client) => Promise<string[]>;
export declare const getBestActiveOrdersIds: (client: Client) => Promise<string[]>;
export declare const getAllOwnOrders: (client: Client, owner: User) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    covering: bigint;
    l1Amount: import("./shared").HexBigInt;
    createdAt: number;
    expirationDate: number;
    activityStatus: import("./shared").ORDER_ACTIVITY_STATUS;
    owner: import("@coinweb/contract-kit").User;
    baseRecipient: import("@coinweb/contract-kit").User;
    txId: string;
}[]>;
export declare const getAllOwnClaims: (client: Client, owner: User) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    createdAt: number;
    executionStatus: import("./shared").REQUEST_EXECUTION_STATUS;
    expirationDate: number;
    fallbackContractId: string;
    fallbackMethodName: string;
    quoteWallet: string;
    requestedOrderId: string;
    txId: string;
}[]>;
export declare const getAllActiveOrders: (client: Client) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    covering: bigint;
    l1Amount: import("./shared").HexBigInt;
    createdAt: number;
    expirationDate: number;
    activityStatus: import("./shared").ORDER_ACTIVITY_STATUS;
    owner: import("@coinweb/contract-kit").User;
    baseRecipient: import("@coinweb/contract-kit").User;
    txId: string;
}[]>;
export declare const getBestOrders: (client: Client) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    covering: bigint;
    l1Amount: import("./shared").HexBigInt;
    createdAt: number;
    expirationDate: number;
    activityStatus: import("./shared").ORDER_ACTIVITY_STATUS;
    owner: import("@coinweb/contract-kit").User;
    baseRecipient: import("@coinweb/contract-kit").User;
    txId: string;
}[]>;
export declare const getBestActiveOrders: (client: Client) => Promise<{
    id: string;
    baseAmount: bigint;
    quoteAmount: bigint;
    collateral: bigint;
    covering: bigint;
    l1Amount: import("./shared").HexBigInt;
    createdAt: number;
    expirationDate: number;
    activityStatus: import("./shared").ORDER_ACTIVITY_STATUS;
    owner: import("@coinweb/contract-kit").User;
    baseRecipient: import("@coinweb/contract-kit").User;
    txId: string;
}[]>;
export declare const getBalance: (client: Client, owner: User) => Promise<import("@coinweb/wallet-lib").GqlIssuedClaim>;
